### ISSUE TITLE
Assely CLI not working in vagrant box

### ISSUE THREAD

**Issue by mawiswiss** [assely/installer#1]
When developing inside a vagrant box, we need to fire commands inside the box or tunnel the command through ssh. However, assely needs to be installed inside the box.

I can't run any commands (e.g wp assely:info). I'll receive the following error:
`Error: Method Assely\Foundation\Console\InfoCommand::() does not exist `

When running `wp help`, all assely commands are listed there.

**Comment by jedrzejchalubek** [comment]
It's framework related, not installer. This error show up when you not provide command argument (`wp assely:info` instead `wp assely:info menus`).

Bug is is already reported here: https://github.com/assely/framework/issues/4, so I close this and please continue further discussions there :) Thanks.
